// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgC1Wh2yHp4_AdZynsBi3Atd7VEfoUNKE',
    appId: '1:139859168650:web:d0792aeeb0bfc0257a4c73',
    messagingSenderId: '139859168650',
    projectId: 'amologicassign',
    authDomain: 'amologicassign.firebaseapp.com',
    storageBucket: 'amologicassign.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBX-5J-mCg6kRyVth0bQ-bCnnQ63Ivyas',
    appId: '1:139859168650:android:65f8854f7ec72b587a4c73',
    messagingSenderId: '139859168650',
    projectId: 'amologicassign',
    storageBucket: 'amologicassign.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxf9atPrqmyCMjlqNQLLnukqHZhk7cxsM',
    appId: '1:139859168650:ios:555edb2d045480547a4c73',
    messagingSenderId: '139859168650',
    projectId: 'amologicassign',
    storageBucket: 'amologicassign.appspot.com',
    iosBundleId: 'com.example.amolgicAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxf9atPrqmyCMjlqNQLLnukqHZhk7cxsM',
    appId: '1:139859168650:ios:555edb2d045480547a4c73',
    messagingSenderId: '139859168650',
    projectId: 'amologicassign',
    storageBucket: 'amologicassign.appspot.com',
    iosBundleId: 'com.example.amolgicAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgC1Wh2yHp4_AdZynsBi3Atd7VEfoUNKE',
    appId: '1:139859168650:web:51a49b03d33747b27a4c73',
    messagingSenderId: '139859168650',
    projectId: 'amologicassign',
    authDomain: 'amologicassign.firebaseapp.com',
    storageBucket: 'amologicassign.appspot.com',
  );
}
